### PR TITLE
Float dihedrals

### PR DESCRIPTION
**Pull request by hnisonoff**
Here my pull request to allow decimal values in the rotamer file

### CODE REVIEW

**Comment by hnisonoff** [comment]
@cuchaz do you want to confirm that this is okay before I merge it? Also could I get new linux and mac builds of the python versions? I currently can build it on my mac but not on the linux cluster I have access to. It looks like I might be missing something called `jmods`??

```
ls -l /usr/lib/jvm/java-11-openjdk-amd64
total 24
drwxr-xr-x  2 root root 4096 May 12 14:25 bin
drwxr-xr-x  4 root root 4096 May 12 14:25 conf
lrwxrwxrwx  1 root root   42 Apr 15 14:12 docs -> ../../../share/doc/openjdk-11-jre-headless
drwxr-xr-x 72 root root 4096 May 12 14:25 legal
drwxr-xr-x  6 root root 4096 May 12 14:26 lib
drwxr-xr-x  4 root root 4096 May 12 14:25 man
-rw-r--r--  1 root root 1161 Apr 15 14:12 release
```

**Comment by cuchaz** [comment]
Looks good to me. Thanks for the PR!

Before I merge it, @gusennan, the Azure problems are unrelated to this change, right?

**Comment by hnisonoff** [comment]
Thanks! Not sure if you saw my above message since I uploaded it right before you responded, but if you have any guidance about the `jmods` issue that would be great. Otherwise if you don't mind emailing me the linux and mac builds, I'd really appreciate it.

**Comment by gusennan** [comment]
@cuchaz should be fine. If something were to change in this PR it would rerun the checks and they'd probably pass since I got the foundation in master between the time @hnisonoff opened and I commented on this post.


@hnisonoff there's a new release here with all of the binaries you may need.
https://github.com/donaldlab/OSPREY3/releases/latest

**Comment by hnisonoff** [comment]
@gusennan thanks! Is it possible to create a release with this merge??

**Comment by gusennan** [comment]
@hnisonoff we'd want to test it out first, but you can still get and use the same binaries that would be in a release here (see the "artifacts" link)

https://dev.azure.com/donaldlab/osprey/_build/results?buildId=103&view=results

**Comment by hnisonoff** [comment]
Sorry I don't see anything in the artifacts link.
[image: image.png]

**Comment by cuchaz** [comment]
Try this link?

https://dev.azure.com/donaldlab/osprey/_build/results?buildId=103&view=artifacts&type=publishedArtifacts

**Comment by hnisonoff** [comment]
Thanks!

**Pull request merged**
